repos:
  # 1. Gitleaks: Secrets aur API Keys pakadne ke liye
  - repo: https://github.com/gitleaks/gitleaks
    rev: v8.30.0
    hooks:
      - id: gitleaks

  # 2. Pre-commit Hooks (Standard): Basic galtiyan rokne ke liye
  - repo: https://github.com/pre-commit/pre-commit-hooks
    rev: v6.0.0
    hooks:
      - id: check-yaml          # YAML file ka syntax check karega
      - id: end-of-file-fixer   # Har file ke end mein khali line ensure karega
      - id: trailing-whitespace # फालतू spaces hata dega
      - id: check-added-large-files # Bahut badi files commit hone se rokega

  # 3. Pyupgrade: Purane Python code ko naye version mein auto-update karega
  - repo: https://github.com/asottile/pyupgrade
    rev: v3.21.2
    hooks:
      - id: pyupgrade

  # 4. Black: Code ko professional tarike se format karega (Sundar banayega)
  - repo: https://github.com/psf/black
    rev: 26.3.1
    hooks:
      - id: black

  # 5. Bandit: Python code mein security bugs (vulnerabilities) dhundega
  - repo: https://github.com/PyCQA/bandit
    rev: 1.9.4
    hooks:
      - id: bandit
        args: ["-lll"] # Sirf high-severity issues dikhayega
